---
title: "Data Science Report"
author: "Rachael Smith"
date: "5/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

*Develop a few novel questions that data can answer*
[ ] Get feedback from 6-8 people on their interest in your questions and summarize this feedback
[ ] Find other examples of people addressing your question
[ ] Present your question to a data scientist/data analyst to get feedback on the quality of the question and if it can be addressed in 2-months.
[ ] Create one .rmd file that has your report
[ ] Have a section for each question
[ ] Be prepared to discuss your results in the upcoming class

\br

##### How do we measure Student Growth in areas of confidence, personal responsbility and love of learning?

\br

##### How do we measure the success of a company's mission statement?

\br



```{r cars}
summary(cars)
```

## Including Plots


```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
