---
title: "Case Study 6"
author: "Rachael Smith"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:  
    keep_md: true
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
---

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

### Take me out to the ball game

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
#install.packages("tidyverse") # run this line once in console to get package
library(tidyverse)
library(Lahman)
library(blscrapeR)
library(pander)
library(blscrapeR)

```

```{r}
# Load and Join all the datasets

player_salaries <- Salaries %>% 
  select(salary, teamID, playerID, lgID, yearID)

player_teams <- Teams %>% 
  select(yearID, teamID, lgID, W, L, LgWin, WSWin, name)

salaries_league <- Salaries %>% 
  left_join(player_teams, by = c("teamID", "yearID"))

player_name <- People %>% 
  select(nameFirst, nameLast, playerID, retroID, bbrefID)

player_college <- CollegePlaying %>% 
  filter(schoolID %in% c("utah", "utahst", "utahvalley", "utdixie", "utslxxo", "utsnojc", "byu")) %>% 
  select(-yearID)

utah_players <- player_college %>% 
  left_join(salaries_league, by = "playerID") %>%
  left_join(player_name, by = "playerID")

utah_players2 <- utah_players %>% 
  select(nameFirst, nameLast, salary, schoolID, yearID, name, W, L, LgWin, WSWin)

utah_players3 <- utah_players2 %>%
  mutate(yearID = as.numeric(yearID)) %>% 
  filter(salary >= 0) %>% 
  unite("Full Name", c(nameFirst, nameLast), sep = " ")

inflation <- inflation_adjust(2017) %>%
  mutate(year = as.numeric(year)) %>% 
  select(year, adj_value)

utah_inflation <- utah_players3 %>%
  left_join(inflation, by = c("yearID" = "year")) %>% 
  mutate(adj_salary = round(salary / adj_value))

```

-----

```{r}
# prep data for graphs

byu_players <- utah_inflation %>% 
  filter(adj_salary >= 1000000) %>%
  group_by(`Full Name`, schoolID) %>% 
  summarise(mean_salary = mean(adj_salary), max_salary = max(adj_salary)) %>%
  select(`Full Name`, schoolID, max_salary, mean_salary)



utah_salary <- utah_inflation %>% 
  filter(schoolID != "byu") %>%
  group_by(schoolID, yearID) %>% 
  summarise(mean_salary = mean(adj_salary))

byu_salary <- utah_inflation %>% 
  filter(schoolID == "byu") %>%
  group_by(schoolID, yearID) %>% 
  summarise(mean_salary = mean(adj_salary))


byu_years <- utah_inflation %>% 
  filter(schoolID == "byu") %>%
  group_by(`Full Name`, yearID) %>% 
  summarise(mean_salary = mean(adj_salary))

```

### Mean Player Professional Salary

```{r message=FALSE, warning=FALSE}
ggplot(mapping = aes(color = schoolID)) +
  geom_point(data = utah_salary, size = 2, mapping = aes (x = yearID, y = mean_salary)) + 
  geom_line(data = utah_salary, size = .25, mapping = aes (x = yearID, y = mean_salary)) + 
  geom_point(data = byu_salary, size = 2.0, mapping = aes (x = yearID, y = mean_salary)) +
  geom_line(data = byu_salary, size = .25, mapping = aes (x = yearID, y = mean_salary)) +
  labs(title = "Mean Professional Baseball Player Salaries Who Attended Utah Colleges", subtitle = "All salaries were adjusted based on 2017 inflation.", x = "Years", y = "Mean Salary", color = "Utah Schools") + 
  scale_y_continuous(breaks = c(0, 1000000, 2000000, 3000000, 4000000,5000000, 6000000, 7000000, 8000000, 9000000), labels = c("$", "$1M", "$2M", "$3M", "$4M","$5M", "$6M", "$7M", "$8M", "$9M")) +
  scale_color_manual(values = c("navyblue", "#d11141", "#00b159", "#00aedb", "#f37735", "#ffc425"), labels = c("BYU", "U of U", "UVU", "Dixie", "SLCC", "Snow College")) +
  scale_x_continuous(breaks = c(1985,1990,1995, 2000, 2005, 2010, 2015), labels = c("1985", "1990", "1995", "2000", "2005", "2010", "2015")) +
  theme_minimal() + 
  theme(legend.position = "bottom")

  
```

### Maximum Player Salary

```{r message=FALSE, warning=FALSE}
ggplot(data = byu_players, mapping = aes(x = reorder(`Full Name`, max_salary), y = max_salary)) +
  geom_bar(stat = "identity", aes(fill = schoolID))+
  geom_boxplot(aes(y = mean_salary, color = "Player Mean")) +
  labs(title = "Maximum Salaries for Professional Baseball Players Who Attended BYU", subtitle = "For Players who made over $1, all salaries were adjusted based on 2017 inflation.", x = "Professional Baseball Players who Attended Utah Schools", y = "Maximum Career Salary in USD", fill = "Utah Schools", color = "Mean Salary") + 
 scale_y_continuous(breaks = c(0, 1000000, 2000000, 3000000, 4000000,5000000, 6000000, 7000000, 8000000, 9000000), labels = c("$", "$1M", "$2M", "$3M", "$4M","$5M", "$6M", "$7M", "$8M", "$9M")) +
  theme(axis.ticks.x = element_blank()) + 
  scale_fill_manual(values = c("navyblue", "#d11141"), labels = c("BYU", "Dixie")) +
  theme_minimal()

```

-----

##### Utah Player Player Mean Salary by Player

```{r}
pander(byu_players)

```

##### BYU Mean Salary By Year

```{r}
pander(byu_salary)
```

