---
title: "Task 9"
author: "Rachael Smith"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:  
    keep_md: true
    toc: true
    toc_float: true
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
---

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
#install.packages("tidyverse") # run this line once in console to get package

library(readr)
library(haven)
library(readxl)
library(downloader)
library(tidyverse)
library(pander)

```


### Background

Reading in the DOW data with 5 different comonly known file types.

-----


### Import Different File Types

##### RDS File

```{r}
# Read in the rds file

rds_file <- read_rds(url("https://github.com/byuistats/data/raw/master/Dart_Expert_Dow_6month_anova/Dart_Expert_Dow_6month_anova.RDS"))

pander(head(rds_file, 10))

```


##### CSV File

```{r plot_data}
# Read in the CSV file

csv_file <- read_csv("https://raw.githubusercontent.com/byuistats/data/master/Dart_Expert_Dow_6month_anova/Dart_Expert_Dow_6month_anova.csv")

pander(head(csv_file, 10))

```

##### DTA File

```{r}
# Read in the dta file

dta_file <- read_dta("https://github.com/byuistats/data/raw/master/Dart_Expert_Dow_6month_anova/Dart_Expert_Dow_6month_anova.dta")

pander(head(dta_file, 10))

```

##### SAV File

```{r tidy_data}
# Read in the sav file

sav_file <- read_sav("https://github.com/byuistats/data/blob/master/Dart_Expert_Dow_6month_anova/Dart_Expert_Dow_6month_anova.sav?raw=true")

pander(head(sav_file, 10))

```

##### XLSX File

```{r}
# Read in the xlsx file

tmpx <- tempfile()

download("https://github.com/byuistats/data/blob/master/Dart_Expert_Dow_6month_anova/Dart_Expert_Dow_6month_anova.xlsx?raw=true", tmpx, mode = "wb")

xlsx_file <- read_xlsx(tmpx)

pander(head(xlsx_file, 10))

```

### Check All Files Are Equal

```{r message=FALSE, warning=FALSE}
all.equal(rds_file, csv_file)
all.equal(rds_file, dta_file)
all.equal(rds_file, sav_file)
all.equal(rds_file, xlsx_file)

```

-----

### Graphic

```{r}
stock <- csv_file %>%
  group_by(variable) %>% 
  select(variable, value)

ggplot(data=stock, aes(x = variable, y = value, color = variable)) +
  geom_boxplot() +
  geom_jitter(height = 0, mapping = aes(alpha = .025, color = variable)) +
  stat_summary(fun.y = mean, geom="errorbar", aes(ymax=..y..,ymin=..y.., group = factor(variable)), 
               width=0.75, linetype="dashed", size=.5, color="black") +
  labs(title = "Performance of DARTS, DJIA, and PROS Stock", subtitle = "From 1990 -1997", x = "Stock Variables", y = "Stock Value", caption = "Black Dashed Line = Mean") +
  theme_minimal()
```

