---
title: "Class Task 13"
author: "Rachael Smith"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:  
    keep_md: true
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
---

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

### Strings and Regular Expression

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
#install.packages("tidyverse") # run this line once in console to get package
library(tidyverse)
library(stringr)

```


```{r}
random_lines2 <- read_lines("https://byuistats.github.io/M335/data/randomletters.txt")

view(random_lines2)

random_lines <- split_lines  %>% 
  str_split("\n") %>% 
  
view(random_lines)
```


```{r}

dat <- readr::read_lines("https://byuistats.github.io/M335/data/randomletters.txt")



dat2 <- str_sub(dat, seq(0,70000, by = 1700))
  
dat2

                            
```


```{r load_data}
# Use this R-Chunk to import all your datasets!
x <- c("\"", "\\")
x
writeLines(x)

"\u00b5"
```

## Background

_Place Task Background Here_

## Data Wrangling

```{r tidy_data}
# Use this R-Chunk to clean & wrangle your data!
dat <- readr::read_lines("https://byuistats.github.io/M335/data/randomletters.txt")

str_length(dat)
str_remove_all(dat, ["ae"])

str_remove_all(dat, "a|e")

str_length(dat)

dat3 <- str_extract_all(dat, "sister")

dat3

quant <- function(rx)str_view_all("aaa";rx)
dat3 <- str_extract_all(dat, "a{3}")

dat4 <- str_extract_all 

dat5 <- str.locate(dat,"aaa")
dat5


dat %>%  str_locate_all("aaa") %>% unlist()

dat %>% str_split(pattern = "[:^alpha:]") %>% str_split("")



```

## Data Visualization

```{r plot_data}
# Use this R-Chunk to plot & visualize your data!
str_count( dat, pattern =c("mom","dad","jim"))
```

## Conclusions
