---
title: "Case Study 5"
author: "Rachael Smith"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:  
    keep_md: true
    toc: true
    toc_float: true
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
---

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

## (Heights) I Can Clean Your Data

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
#install.packages("tidyverse") # run this line once in console to get package

library(tidyverse)
library(haven)
library(readr)
library(foreign)
library(readxl)
library(downloader)
library(janitor)

```

## Background

_Place Task Background Here_

## Data Wrangling

```{r tidy_data}
# Use this R-Chunk to clean & wrangle your data!

Height <- read_excel("Case_Study_05/Height.xlsx", skip = 2)

Height2 <- remove_empty(Height, which = c("rows", "cols"), quiet = TRUE)

long_height <- Height2 %>%
  rename("country" = `Continent, Region, Country`) %>%
  pivot_longer(cols = c(3:20), names_to = "decade2", values_to = "height.cm") %>%
  separate(decade2, into = c("century", "decade", "year"), sep = c(2, 3, 4)) %>%
  select(Code, country, century, decade, year, height.cm)

View(long_height)

```

```{r}

height_1 <- long_height %>% 
  summarise(height.in = prod(height.cm, 0.39), height.cm = height.cm) %>%
  select(Code, country, century, decade, year, height.cm, height.in)

```


## Data Visualization

```{r plot_data}
# Use this R-Chunk to plot & visualize your data!
germ_height <- long_height %>% 
  filter(country == "Germany") %>%
  group_by(decade) %>%
  summarise(height.in = prod(height.cm, 0.39)) %>%
  select(Code, country, height.cm, year_decade, height.in)


View(germ_height)
```

## Conclusions
