---
title: "Task 10"
author: "Rachael Smith"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:  
    keep_md: true
    toc: true
    toc_float: true
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
---

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
#install.packages("tidyverse") # run this line once in console to get package

library(dplyr)
library(tidyr)
library(tidyverse)
library(pander)
library(stringr)
```

```{r load_data}
# Use this R-Chunk to import all your datasets!
tmpx <- tempfile()

download("https://github.com/byuistats/data/blob/master/Dart_Expert_Dow_6month_anova/Dart_Expert_Dow_6month_anova.xlsx?raw=true", tmpx, mode = "wb")

xlsx_file <- read_xlsx(tmpx)

pander(head(xlsx_file, 5))
  
sep_xl <- xlsx_file %>%
  separate(contest_period, into = c("start", "end"), sep = "-") %>%
  mutate(end_year = substr(end, nchar(end)-3, nchar(end)))

View(sep_xl)


  
```


## Background

_Place Task Background Here_

## Data Wrangling

```{r tidy_data}
# Use this R-Chunk to clean & wrangle your data!
timeline <- tibble(
  year = c(1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998),
  month = c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")) %>% 
  pivot_wider(months_end = months, year_end = year)

time_end <- sep_xl %>% 
  mutate(month_end = "month_end", year = "year_end")
time_end
```

## Data Visualization

```{r plot_data}
# Use this R-Chunk to plot & visualize your data!

```

## Conclusions
